### ISSUE TITLE
Compilation issue with MiddlewareError

### ISSUE THREAD

**Issue by aellwein** [pfz4/axum-oidc#1]
Hi,
i am trying to use this package - looks promising, but i get strange error which i cannot explain
```
error[E0599]: no method named `into_response` found for enum `MiddlewareError` in the current scope
   --> server/src/main.rs:79:15
    |
79  |             e.into_response()
    |               ^^^^^^^^^^^^^ method not found in `MiddlewareError`
    |
   ::: /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-core-0.3.4/src/response/into_response.rs:128:8
    |
128 |     fn into_response(self) -> Response;
    |        ------------- the method is available for `MiddlewareError` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
25  + use axum_core::response::into_response::IntoResponse;
    |

error[E0599]: no method named `into_response` found for enum `MiddlewareError` in the current scope
   --> server/src/main.rs:85:15
    |
85  |             e.into_response()
    |               ^^^^^^^^^^^^^ method not found in `MiddlewareError`
    |
   ::: /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-core-0.3.4/src/response/into_response.rs:128:8
    |
128 |     fn into_response(self) -> Response;
    |        ------------- the method is available for `MiddlewareError` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
25  + use axum_core::response::into_response::IntoResponse;
    |

For more information about this error, try `rustc --explain E0599`.
error: could not compile `server` (bin "server") due to 2 previous errors
```
I've put the source code i've created with axum-oidc here: 
https://gist.github.com/aellwein/18a3d5b46770fb2f3d5274a3d765e0d0

There is also Cargo.toml included - i am using axum-0.7.2 along with some additional dependencies, maybe 
these have some impact here.

**Comment by pfz4** [comment]
Hello,
thank you for reporting the issue.
The `0.1.1` Version of `axum-oidc`was build against axum `0.6.*`. 
I've published a version that supports axum `0.7.*` as version `0.2.0`

**Comment by aellwein** [comment]
Hello Paul,

confirmed - it works with the new release ``0.2.0``. Thank you very much for the fast help 
and for this very useful software package!

Best Regards,
Alex
